# import arguments passed on: environment
Import('env')

# create executable for testing, note that:
# the library for the 'BDD_ID and Manager classes are linked (libBDD located in '../src/')
# FranctionTest object is also linked ('../src/unittest/ManagerTest.o')
program = env.Program(target = "testrunner", source = ['testrunner.cpp', '../src/unittest/ManagerTest.o'], LIBS=['cppunit','libBDD'], LIBPATH='../src/')

# make sure that the tests can be run
# for that on the root directory (directory with the Sconstruct file)
# type on the console: "scons test"
# Alias runs the tests ([program], program[0].path) when the argument 'test' is given when callin scons
test_alias = Alias('test', [program], program[0].path)
AlwaysBuild(test_alias)

